debug: true
server:
  # Memory limit in MB for HistoryDB
  memory: 100
  # Custom processor name
  # Only available when we can not get CPU info
  #  model:
  # Your server ID
  id: "N0CALL"
  # Passcode for the server ID
  passcode: 0
  # Setting of http status panel
  status:
    host: "[::]"
    port: 14501
  # Setting of aprs server
  # Mode: fullfeed [Everything] / igate [IGate / Client Port]
  listeners:
    -
      name: "Full Feed"
      mode: "fullfeed"
      protocol: "tcp"
      host: "[::]"
      port: 10152
      visible: "hidden"
    - name: "Full Feed"
      mode: "fullfeed"
      protocol: "udp"
      host: "[::]"
      port: 10152
      visible: "hidden"
    - name: "Client-Defined Filters"
      mode: "igate"
      protocol: "tcp"
      host: "[::]"
      port: 14580
    - name: "Client-Defined Filters"
      mode: "igate"
      protocol: "udp"
      host: "[::]"
      port: 14580
  #    - name: "350 km from my position"
  #      mode: "igate"
  #      protocol: "tcp"
  #      host: "[::]"
  #      port: 20350
  #      filter: "m/350"
  #    - name: "350 km from my position"
  #      mode: "igate"
  #      protocol: "udp"
  #      host: "[::]"
  #      port: 20350
  #      filter: "m/350"
  # Setting of uplink
  # Mode: full [Full Feed] / ro [Read-Only]
  uplinks:
    -
      name: "Core Rotate"
      mode: "full"
      protocol: "tcp"
      host: "rotate.aprs.net"
      port: 10152
admin:
  name: "Name, MYCALL"
  email: "email@example.com"
log:
  file: "logs/app.log"
  maxSize: 100
  maxBackups: 10
  maxAge: 30
  compress: true
